backend: 
    name: github
    repo: eoinf91/first-gatsby-blog

media_folder: static/assets
public_folder: assets

collections:
    - label: "Pages"
      name: "pages"
      files:
        - label: "Home Page"
          name: "home"
          file: "content/home.md"
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Intro text, name: intro, widget: text}
            - {label: Image, name: image, widget: image}
        - label: "Blog"
          name: "blog"
          folder: "_posts/blog"
          create: true
          identifier_field: name
          fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Publish Date", name: "date", widget: "datetime"}
            - {label: "Featured Image", name: "thumbnail", widget: "image"}
            - {label: "Body", name: "body", widget: "markdown"}